import type { Metadata } from "next";
import { Public_Sans } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "NPM Chart",
  description: "Generated by create next app",
};

const PublicSans = Public_Sans({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${PublicSans.className}`}>
        {children}
      </body>
    </html>
  );
}
